## jdbc ≈‰÷√
jdbc:
  url: jdbc:mysql://47.98.116.157:3306/druid
  userName: root
  password: sxli
  dbType: mysql
  driverClassName: com.mysql.cj.jdbc.Driver
  maxActive: 20
  minIdle: 10
  ## ≤‚ ‘ø’œ–¡¨Ω”SQL
  validationQuery: SELECT 1
  ## ø™∆Ù≤‚ ‘ø’œ–
  testWhileIdle: true

## mybatis ≈‰÷√
mybatis:
  mapper-locations: classpath:mapper/*.xml
  type-aliases-package: com.sxli.druiddemo.domain